language: php

services: mysql

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install
  - mysql -e 'CREATE DATABASE class8;'

# script: vendor/bin/phpunit --verbose
script: phpunit --coverage-text --configuration phpunit.xml